const list = ["angle", "armoire", "banc", "bureau", "cabinet",
"carreau", "chaise", "classe", "clé", "coin", "couloir", "dossier",
"eau", "école", "écriture", "entrée", "escalier", "étagère", "étude",
"extérieur", "fenêtre", "intérieur", "lavabo", "lecture", "lit", "marche",
"matelas", "maternelle", "meuble", "mousse", "mur", "peluche", "placard",
"plafond", "porte", "portemanteau", "poubelle", "radiateur", "rampe",
"récréation", "rentrée", "rideau", "robinet", "salle", "savon", "serrure",
"serviette", "siège", "sieste", "silence", "sol", "sommeil", "sonnette",
"sortie", "table", "tableau", "tabouret", "tapis", "tiroir", "toilette",
"vitre", "chanter", "chercher", "choisir", "chuchoter", "coller", "colorier",
"commencer", "comparer", "compter", "construire", "continuer", "copier",
"couper", "déchirer", "décoller", "décorer", "découper", "demander", "démolir",
"dessiner", "dire", "discuter", "écouter", "écrire", "effacer",
"entendre", "entourer", "envoyer", "faire", "finir", "fouiller", "goûter",
"imiter", "laisser", "lire", "mettre", "montrer", "parler",
"peindre", "plier", "poser", "prendre", "préparer", "ranger", "réciter",
"recommencer", "regarder", "remettre", "répéter", "répondre", "sentir",
"souligner", "tailler", "se taire", "tenir", "terminer", "toucher",
"travailler", "trier", "adroit", "difficile", "dur", "facile", "lisse",
"maladroit", "pointu", "rugueux", "tordu", "dangereux", "épais", "fort",
"gauche", "groupé", "immobile", "rond", "serré", "souple", "déçu", "triste",
"chaud", "froid", "pluvieux", "nuageux", "humide", "gelé", "instable", "changeant",
"abricot", "ail", "aliment", "ananas", "banane", "bifteck", "café", "carotte",
"cerise", "chocolat", "chou", "citron", "citrouille", "clémentine", "concombre",
"coquillage", "corbeille", "crabe", "crevette", "endive", "farine", "fraise",
"framboise", "fromage", "fruit", "gâteau", "haricot", "huile", "légume", "marchand",
"melon", "monnaie", "navet", "noisette", "noix", "nourriture", "oignon", "orange",
"panier", "pâtes", "pêche", "persil", "poire", "poireau", "pomme",
"prix", "prune", "queue", "raisin", "riz", "salade", "sucre", "thé",
"tomate", "viande", "vin", "adresse", "appartement", "ascenseur", "balcon", "boucherie",
"boulanger", "boulangerie", "boutique", "bus", "caniveau", "caravane", "carrefour", "cave",
"charcuterie", "cinéma", "cirque", "cloche", "clocher", "clown", "coiffeur",
"courrier", "croix", "église", "embouteillage", "endroit", "enveloppe",
"essence", "facteur", "fleuriste", "foire", "hôpital", "hôtel", "immeuble", "incendie",
"laisse", "magasin", "manège", "médicament", "moineau", "monde", "monument", "ouvrier",
"palais", "panneau", "paquet", "parc", "passage", "pharmacie", "pharmacien", "piscine",
"place", "police", "policier", "pompier", "poste", "promenade", "quartier", "square",
"timbre", "travaux", "usine", "village", "ville", "voisin", "volet", "ambulance", "bosse",
"champignon", "dentiste", "docteur", "fièvre", "front", "gorge", "infirmier", "infirmière",
"jambe", "larme", "médecin", "menton", "mine", "ordonnance", "pansement", "peau", "piqûre",
"poison", "sang", "santé", "squelette", "trousse", "argent", "aspirateur", "bague", "barrette",
"bijou", "bracelet", "brosse", "cadre", "canapé", "chambre", "cheveu", "chiffon", "cil",
"coffre", "coffret", "collier", "couette", "coussin", "couverture", "dent", "dentifrice",
"drap", "fauteuil", "frange", "glace", "lampe", "lit", "ménage", "or",
"oreiller", "parfum", "peigne", "pouf", "poupée", "poussette", "poussière", "shampoing",
"sourcil", "trésor", "tube", "vase"]

export default list